# Site settings
title: Artyom Pertsovsky
email: artyom@pertsovsky.com
description: >
  Artyom Pertsovsky personal website
url: "http://artyom.pertsovsky.com" # the base hostname & protocol for your site
github_username: versality

# Build settings
markdown: kramdown
