# Site settings
title: Artyom Pertsovsky
email: artyom@pertsovsky.com
description: >
  Artyom Pertsovsky Website.
  Ruby on Rails, EmberJS, Python, Git, Agile, Linux,
  JavaScript, CSS, MySQL, PostgreSQL, ElasticSearch, Redis.
keywords: "Артем,Перцовский,Web,Analyst,Architect,Developer"
author: "Artyom Pertsovsky"
url: "http://artyom.pertsovsky.com" # the base hostname & protocol for your site
github_username: versality

# Build settings
markdown: kramdown
